#!/usr/bin/env bash
# LICENSE for this script is at the end of this file
#
# The launcher is designed to simplify the launch of Linux applications and move the home directory
# to avoid conflicts between different versions of the same application.

# Allows you to avoid configuration file conflicts when installing different versions of the same application.
ISHMoveHomeDir="true"
UseExtraLibs="false"

PathToScript="$( dirname "$(readlink -f "$0")")"
FolderBaseName="$( basename "$PathToScript")"

## DO NOT TOUCH THIS WITHOUT A SERIOUS REASON! ##
ISHPogramArch="other"
ISHProgramFName="other"
ISHInstallPathUser="$HOME/portsoft"
ISHInstallPathUserFull="$ISHInstallPathUser/$ISHPogramArch/$ISHProgramFName"
ISHInstallPathSystem="/portsoft"
ISHInstallPathSystemFull="$ISHInstallPathSystem/$ISHPogramArch/$ISHProgramFName"
if [ ! -e "$ISHInstallPathUserFull" ]; then if ! mkdir -p "$ISHInstallPathUserFull"; then echo "No_Rights"; fi; fi

###########################################
## THESE VARIABLES NEED TO BE CONFIGURED ##
## ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ##
ProgramFolder="$PathToScript/program"      # Path to the program directory
ExeFolder="$ProgramFolder/bin"            # Path to the directory with executable files
Executable="$ExeFolder/ExeFile"           # Main executable file
ExtraLibsFolder="$PathToScript/libs"       # Extra libraries

if [ "$PathToScript" == "$ISHInstallPathSystemFull" ]; then UserDataFolder="$ISHInstallPathUserFull/userdata"
elif [ "$PathToScript" == "$ISHInstallPathUserFull" ]; then UserDataFolder="$ISHInstallPathUserFull/userdata"
elif 
else UserDataFolder="$PathToScript/userdata"; fi

## Space for additional variables and actions ###
#export SOME_IMPORTANT_VARIABLE="example"
## Space for additional variables and actions ###

export PATH="$ExeFolder:$PATH" # Use ":" for separation

if [ "$ISHMoveHomeDir" == "true" ]; then
	export HOME="$UserDataFolder"
	export HOMECONFIGS="$UserDataFolder"
	#export XDG_DATA_DIRS="$HOMECONFIGS/.local/share:$XDG_DATA_DIRS"
	export XDG_DATA_HOME="$HOMECONFIGS/.local/share"
	export XDG_STATE_HOME="$HOMECONFIGS/.local/state"
	export XDG_CONFIG_HOME="$HOMECONFIGS/.config"
	export XDG_CACHE_HOME="$HOMECONFIGS/.cache"
fi

if [ "$UseExtraLibs" == "true" ]; then
	if [ -z "$LD_LIBRARY_PATH" ];
		then export LD_LIBRARY_PATH="$ExtraLibsFolder"
		else export LD_LIBRARY_PATH="$ExtraLibsFolder:$LD_LIBRARY_PATH" # Use ":" for separation
	fi
fi

if [ -e "$Executable" ]; then
	if ! [[ -x "$Executable" ]]; then if ! chmod +x "$Executable"; then echo "chmod error"; fi; fi
	cd "$ExeFolder" || exit
	"$Executable" "$@"
	exit_code="$?"
else
	exit_code="Executable not found..."
fi

if [[ "$exit_code" != "0" ]]; then
	StringMessage="bash -c 'echo \"-\"; echo \"$Executable\"; echo \"-\"; echo \"WARNING! EXIT CODE - $exit_code\"; echo \"The program has terminated incorrectly!\"; echo \"Is the program incompatible with the current OS?\"; echo \"Does the program contain errors?\"; read pause'"
	
	export PATH="/usr/local/bin:/usr/bin:/bin:$PATH"
	export LD_LIBRARY_PATH=""
	
	terminal_executable="x-terminal-emulator"
	if ! type "x-terminal-emulator" &> /dev/null; then
		if type "xfce4-terminal" &> /dev/null; then terminal_executable="xfce4-terminal"
		elif type "konsole" &> /dev/null; then terminal_executable="konsole"
		elif type "gnome-terminal" &> /dev/null; then terminal_executable="gnome-terminal"
		elif type "xterm" &> /dev/null; then terminal_executable="xterm"
		elif type "uxterm" &> /dev/null; then terminal_executable="uxterm"; fi
	fi
	
	$terminal_executable -e "$StringMessage"
fi

# MIT License
#
# Copyright (c) 2025 Chimbal
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
